
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  
  howIworkSidebar: [{type: 'autogenerated', dirName: 'how-i-work'}],
  portfolioSidebar: [{type: 'autogenerated', dirName: 'portfolio'}],
  researchSidebar: [{type: 'autogenerated', dirName: 'research'}]

};

export default sidebars;
